### ISSUE TITLE
Not all field are retrieved

### ISSUE THREAD

**Issue by babuganesh2000** [Delapro/PSDBF#1]
$FNr = 1, i had to change this to $FNr = 0 to get the missing column

**Comment by Delapro** [comment]
Strange. But when you set $FNr=0 you will get the deleted flag, which is represented as the deleted property.

**Comment by babuganesh2000** [comment]
possibly the earlier code which we used was foxpro drive which pulled the deleted column. So we have to make it consistent to change the code to pull the deleted column as well. thanks
